# common settings for each database
common: &common
  adapter: mysql
  username: mnielsen
  password: 
  host: localhost
  database: <%= SERVER_NAME %>

test:
  <<: *common

development:
  <<: *common

production:
  <<: *common
  adapter: postgres
