# common settings for each database
common: &common
  adapter: postgres
  username: mnielsen
  password: 
  host: localhost

test:
  <<: *common
  database: herofu

development:
  <<: *common
  database: herofu

production:
  <<: *common
  database: herofu
